services:
  uptime-kuma:
    container_name: kuma
    image: louislam/uptime-kuma:${UPTIME_KUMA_VERSION}
    restart: unless-stopped
    labels:
      - traefik.http.routers.uptimekuma.rule=Host(`${UPTIME_KUMA_DOMAIN}`)
      - traefik.http.routers.uptimekuma.entrypoints=websecure
      - traefik.http.routers.uptimekuma.tls.certresolver=sslresolver
      - traefik.http.services.uptimekuma.loadbalancer.server.port=3001
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    volumes:
      - ${BASE_PATH}/kuma-data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    expose:
      - 3001

  reverse-proxy:
    container_name: traefik
    image: traefik:${TRAEFIK_VERSION}
    command:
      - "--api.insecure=true"
      - "--accesslog=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.sslresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.sslresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.sslresolver.acme.storage=/lets-encrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - 443:443
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${BASE_PATH}/lets-encrypt/:/lets-encrypt/
    labels:
      - traefik.enable=false
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower:${WATCHTOWER_VERSION}
    container_name: watchtower
    command:
      - "--label-enable"
      - "--rolling-restart"
      - "--interval"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
